alter table licitatii add column if not exists formular_config_json jsonb;
alter table aplicari add column if not exists raspunsuri_formular_json jsonb not null default '{}'::jsonb;

update licitatii
set formular_config_json = '{"version":1,"sections":[{"id":"date-identificare","title":"Date de identificare","fields":[{"id":"nume","label":"Nume","type":"text","source":"standard","bind":"nume","required":true},{"id":"prenume","label":"Prenume","type":"text","source":"standard","bind":"prenume","required":true},{"id":"email","label":"Email","type":"text","source":"standard","bind":"email","required":true},{"id":"telefon","label":"Telefon","type":"text","source":"standard","bind":"telefon"},{"id":"domeniu_studii","label":"Domeniu studii","type":"select","source":"standard","bind":"domeniu_studii","optionsSource":"study_domains","required":true,"scoring":{"factorCod":"F2.1","mode":"select_map"}},{"id":"studii_detalii","label":"Detalii studii","type":"textarea","source":"standard","bind":"studii_detalii"},{"id":"are_cor_242401","label":"Detin certificat Formator COR 242401","type":"checkbox","source":"standard","bind":"are_cor_242401","required":true},{"id":"ani_management","label":"Ani experienta management","type":"number","source":"standard","bind":"ani_management","min":0},{"id":"bio","label":"Profil profesional scurt","type":"textarea","source":"standard","bind":"bio"}]},{"id":"contracte","title":"Contracte si experienta","fields":[{"id":"contracte","label":"Contracte","type":"contract_list","required":true}]},{"id":"documente","title":"Documente justificative","fields":[{"id":"documente","label":"Documente","type":"document_upload","requiredDocumentTypes":["recomandare","contract","diploma","certificat"]}]}]}'::jsonb
where formular_config_json is null;

alter table licitatii alter column formular_config_json set default '{"version":1,"sections":[{"id":"date-identificare","title":"Date de identificare","fields":[{"id":"nume","label":"Nume","type":"text","source":"standard","bind":"nume","required":true},{"id":"prenume","label":"Prenume","type":"text","source":"standard","bind":"prenume","required":true},{"id":"email","label":"Email","type":"text","source":"standard","bind":"email","required":true},{"id":"telefon","label":"Telefon","type":"text","source":"standard","bind":"telefon"},{"id":"domeniu_studii","label":"Domeniu studii","type":"select","source":"standard","bind":"domeniu_studii","optionsSource":"study_domains","required":true,"scoring":{"factorCod":"F2.1","mode":"select_map"}},{"id":"studii_detalii","label":"Detalii studii","type":"textarea","source":"standard","bind":"studii_detalii"},{"id":"are_cor_242401","label":"Detin certificat Formator COR 242401","type":"checkbox","source":"standard","bind":"are_cor_242401","required":true},{"id":"ani_management","label":"Ani experienta management","type":"number","source":"standard","bind":"ani_management","min":0},{"id":"bio","label":"Profil profesional scurt","type":"textarea","source":"standard","bind":"bio"}]},{"id":"contracte","title":"Contracte si experienta","fields":[{"id":"contracte","label":"Contracte","type":"contract_list","required":true}]},{"id":"documente","title":"Documente justificative","fields":[{"id":"documente","label":"Documente","type":"document_upload","requiredDocumentTypes":["recomandare","contract","diploma","certificat"]}]}]}'::jsonb;
alter table licitatii alter column formular_config_json set not null;
